version: "3"
services:
  database:
    container_name: database
    image: mysql:latest
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=payment_db
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3307

  application:
    build: .
    environment:
      - spring.datasource.url= jdbc:mysql://localhost:3307/payment_db?user=test&password=1234
      - spring.sql.init.mode=always
    ports:
      - 8080:8080
    depends_on:
      - database


