version: "3.0"
services:
  database:
    image: mysql:5.7
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=payment_db
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3307
    networks:
      - springboot-mysql-net

  spring-boot:
    container_name: spring-boot
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://database:3307/payment_db?useUnicode=true&serverTimezone=Asia/Seoul
      - spring.datasource.username=test
      - spring.datasource.password=1234
      - spring.sql.init.mode=always
    ports:
      - 8080:8080
    depends_on:
      - database
    links:
      - database
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge
