version: "3.0"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=test
      - MYSQL_PASSWORD=1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql

  spring-boot:
    container_name: spring-boot
#    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://db:3306/payment_db?useUnicode=true&serverTimezone=Asia/Seoul
      - spring.datasource.username=test
      - spring.datasource.password=1234
      - spring.sql.init.mode=always
    ports:
      - 8080:8080
    depends_on:
      - db